# Generated by Django 5.1.5 on 2025-02-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='Default bio text', max_length=100),
            preserve_default=False,
        ),
    ]
